In [ ]:
import pandas as pd
df = pd.read_csv('UserCarData.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7906 entries, 0 to 7905
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sales_ID           7906 non-null   int64
 1   name               7906 non-null   object
 2   year               7906 non-null   int64
 3   selling_price      7906 non-null   int64
 4   km_driven          7906 non-null   int64
 5   Region             7906 non-null   object
 6   State or Province  7906 non-null   object
 7   City               7906 non-null   object
 8   fuel               7906 non-null   object
 9   seller_type        7906 non-null   object
 10  transmission       7906 non-null   object
 11  owner              7906 non-null   object
 12  mileage            7906 non-null   float64
 13  engine             7906 non-null   int64
 14  max_power          7906 non-null   float64
 15  torque             7906 non-null   object
 16  seats              7906 non-null   int64
 17  sold               7906 non-null   object
dtypes: float64(2), int64(6), object(10)
memory usage: 1.1+ MB

In [ ]:
df.describe()

,Sales_ID,year,selling_price,km_driven,mileage,engine,max_power,seats
count,7906.000000,7906.000000,7.906000e+03,7.906000e+03,7906.000000,7906.000000,7906.000000,7906.000000
mean,4070.106248,2013.983936,6.498137e+05,6.918866e+04,19.419861,1458.708829,91.587374,5.416393
std,2345.770159,3.863695,8.135827e+05,5.679230e+04,4.036263,503.893057,35.747216,0.959208
min,1.000000,1994.000000,2.999900e+04,1.000000e+00,0.000000,624.000000,32.800000,2.000000
25%,2037.250000,2012.000000,2.700000e+05,3.500000e+04,16.780000,1197.000000,68.050000,5.000000
50%,4076.500000,2015.000000,4.500000e+05,6.000000e+04,19.300000,1248.000000,82.000000,5.000000
75%,6102.000000,2017.000000,6.900000e+05,9.542500e+04,22.320000,1582.000000,102.000000,5.000000
max,8128.000000,2020.000000,1.000000e+07,2.360457e+06,42.000000,3604.000000,400.000000,14.000000

In [ ]:
df

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
0,1,Maruti,2014,450000,145500,East,District of Columbia,Washington,Diesel,Individual,Manual,First_Owner,23.40,1248,74.00,190Nm@ 2000rpm,5,Y
1,2,Skoda,2014,370000,120000,East,New York,New York City,Diesel,Individual,Manual,Second_Owner,21.14,1498,103.52,250Nm@ 1500-2500rpm,5,Y
2,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.70,1497,78.00,"12.7@ 2,700(kgm@ rpm)",5,Y
3,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.00,1396,90.00,22.4 kgm at 1750-2750rpm,5,Y
4,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.10,1298,88.20,"11.5@ 4,500(kgm@ rpm)",5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,8124,Hyundai,2013,320000,110000,Central,Texas,Plano,Petrol,Individual,Manual,First_Owner,18.50,1197,82.85,113.7Nm@ 4000rpm,5,N
7902,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.80,1493,110.00,"24@ 1,900-2,750(kgm@ rpm)",5,N
7903,8126,Maruti,2009,382000,120000,Central,Texas,Port Arthur,Diesel,Individual,Manual,First_Owner,19.30,1248,73.90,190Nm@ 2000rpm,5,N
7904,8127,Tata,2013,290000,25000,East,Massachusetts,Lunenburg,Diesel,Individual,Manual,First_Owner,23.57,1396,70.00,140Nm@ 1800-3000rpm,5,N
7905,8128,Tata,2013,290000,25000,East,Maine,Augusta,Diesel,Individual,Manual,First_Owner,23.57,1396,70.00,140Nm@ 1800-3000rpm,5,N

In [ ]:
df.groupby(by='owner').agg({'owner':'count'})

                    owner
owner
First_Owner          5215
Fourth_Above_Owner    160
Second_Owner         2016
Test_Drive_Car          5
Third_Owner           510

In [ ]:
df.groupby(by='State or Province').agg({'State or Province':'count'})

                      State or Province
State or Province
Alabama                             106
Arizona                             115
Arkansas                            107
California                          901
Colorado                            154
Connecticut                          63
Delaware                             15
District of Columbia                 68
Florida                             425
Georgia                             187
Idaho                                89
Illinois                            489
Indiana                             213
Iowa                                123
Kansas                              112
Kentucky                             55
Louisiana                            66
Maine                               110
Maryland                            144
Massachusetts                       191
Michigan                            305
Minnesota                           169
Mississippi                          64
Missouri                            141
Montana                              38
Nebraska                             58
Nevada                               39
New Hampshire                        47
New Jersey                          154
New Mexico                           71
New York                            491
North Carolina                      222
North Dakota                         33
Ohio                                321
Oklahoma                             95
Oregon                              129
Pennsylvania                        235
Rhode Island                         17
South Carolina                       81
South Dakota                         22
Tennessee                           135
Texas                               499
Utah                                133
Vermont                              50
Virginia                            167
Washington                          295
West Virginia                        33
Wisconsin                           117
Wyoming                              12

In [ ]:
df1=df[df.torque.str.contains('kgm')]

In [ ]:
# xóa ký tự "kgm@ rpm" trong cột torque
df1['torque']=df1['torque'].str.replace('(kgm@ rpm)','',regex=True)

<ipython-input-50-61fbf2a604e5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['torque']=df1['torque'].str.replace('(kgm@ rpm)','',regex=True)

In [ ]:
df1

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
2,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.7,1497,78.0,"12.7@ 2,700()",5,Y
3,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.0,1396,90.0,22.4 kgm at 1750-2750rpm,5,Y
4,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.1,1298,88.2,"11.5@ 4,500()",5,Y
6,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,Individual,Manual,First_Owner,17.3,1061,57.5,"7.8@ 4,500()",5,Y
16,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,Individual,Manual,Second_Owner,23.0,1396,90.0,22.4 kgm at 1750-2750rpm,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7861,8083,Ford,2007,125000,110000,West,Washington,Yakima,Diesel,Individual,Manual,Third_Owner,17.8,1399,68.0,"16.3@ 2,000()",5,N
7882,8105,Honda,2006,160000,70000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,16.9,1497,100.0,"13.5@ 4,800()",5,N
7883,8106,Honda,2004,135000,120000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,13.0,1343,90.0,11.3kgm@ 4700rpm,5,N
7891,8114,Toyota,2010,425000,129000,South,North Carolina,Mooresville,Diesel,Individual,Manual,First_Owner,12.8,2494,102.0,20.4@ 1400-3400(),8,N
7902,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.8,1493,110.0,"24@ 1,900-2,750()",5,N

In [ ]:
# xóa ký tự "kgm" trong cột torque
df1['torque']=df1['torque'].str.replace('kgm','',regex=True)

<ipython-input-52-fdc4ee188a08>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['torque']=df1['torque'].str.replace('kgm','',regex=True)

In [ ]:
df1

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
2,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.7,1497,78.0,"12.7@ 2,700()",5,Y
3,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.0,1396,90.0,22.4 at 1750-2750rpm,5,Y
4,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.1,1298,88.2,"11.5@ 4,500()",5,Y
6,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,Individual,Manual,First_Owner,17.3,1061,57.5,"7.8@ 4,500()",5,Y
16,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,Individual,Manual,Second_Owner,23.0,1396,90.0,22.4 at 1750-2750rpm,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7861,8083,Ford,2007,125000,110000,West,Washington,Yakima,Diesel,Individual,Manual,Third_Owner,17.8,1399,68.0,"16.3@ 2,000()",5,N
7882,8105,Honda,2006,160000,70000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,16.9,1497,100.0,"13.5@ 4,800()",5,N
7883,8106,Honda,2004,135000,120000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,13.0,1343,90.0,11.3@ 4700rpm,5,N
7891,8114,Toyota,2010,425000,129000,South,North Carolina,Mooresville,Diesel,Individual,Manual,First_Owner,12.8,2494,102.0,20.4@ 1400-3400(),8,N
7902,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.8,1493,110.0,"24@ 1,900-2,750()",5,N

In [ ]:
# thay thế ký tự "at" thành "@" trong cột torque
df1['torque']=df1['torque'].str.replace('at','@',regex=True)

<ipython-input-54-42e46feb1133>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['torque']=df1['torque'].str.replace('at','@',regex=True)

In [ ]:
df1

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
2,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.7,1497,78.0,"12.7@ 2,700()",5,Y
3,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.0,1396,90.0,22.4 @ 1750-2750rpm,5,Y
4,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.1,1298,88.2,"11.5@ 4,500()",5,Y
6,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,Individual,Manual,First_Owner,17.3,1061,57.5,"7.8@ 4,500()",5,Y
16,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,Individual,Manual,Second_Owner,23.0,1396,90.0,22.4 @ 1750-2750rpm,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7861,8083,Ford,2007,125000,110000,West,Washington,Yakima,Diesel,Individual,Manual,Third_Owner,17.8,1399,68.0,"16.3@ 2,000()",5,N
7882,8105,Honda,2006,160000,70000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,16.9,1497,100.0,"13.5@ 4,800()",5,N
7883,8106,Honda,2004,135000,120000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,13.0,1343,90.0,11.3@ 4700rpm,5,N
7891,8114,Toyota,2010,425000,129000,South,North Carolina,Mooresville,Diesel,Individual,Manual,First_Owner,12.8,2494,102.0,20.4@ 1400-3400(),8,N
7902,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.8,1493,110.0,"24@ 1,900-2,750()",5,N

In [ ]:
# Xóa ký tự "rpm" trong cột torque
df1['torque']=df1['torque'].str.replace('rpm','',regex=True)

<ipython-input-58-39db458a2481>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['torque']=df1['torque'].str.replace('rpm','',regex=True)

In [ ]:
df1

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
2,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.7,1497,78.0,"12.7@ 2,700()",5,Y
3,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.0,1396,90.0,22.4 @ 1750-2750,5,Y
4,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.1,1298,88.2,"11.5@ 4,500()",5,Y
6,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,Individual,Manual,First_Owner,17.3,1061,57.5,"7.8@ 4,500()",5,Y
16,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,Individual,Manual,Second_Owner,23.0,1396,90.0,22.4 @ 1750-2750,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7861,8083,Ford,2007,125000,110000,West,Washington,Yakima,Diesel,Individual,Manual,Third_Owner,17.8,1399,68.0,"16.3@ 2,000()",5,N
7882,8105,Honda,2006,160000,70000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,16.9,1497,100.0,"13.5@ 4,800()",5,N
7883,8106,Honda,2004,135000,120000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,13.0,1343,90.0,11.3@ 4700,5,N
7891,8114,Toyota,2010,425000,129000,South,North Carolina,Mooresville,Diesel,Individual,Manual,First_Owner,12.8,2494,102.0,20.4@ 1400-3400(),8,N
7902,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.8,1493,110.0,"24@ 1,900-2,750()",5,N

In [ ]:
df1[['torque1','rpm']]=df1['torque'].str.split("@",expand = True)

<ipython-input-62-61cfd87ddbdc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['torque1','rpm']]=df1['torque'].str.split("@",expand = True)
<ipython-input-62-61cfd87ddbdc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[['torque1','rpm']]=df1['torque'].str.split("@",expand = True)

In [ ]:
df1=df1.drop(columns=['torque'])

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 492 entries, 2 to 7902
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sales_ID           492 non-null    int64
 1   name               492 non-null    object
 2   year               492 non-null    int64
 3   selling_price      492 non-null    int64
 4   km_driven          492 non-null    int64
 5   Region             492 non-null    object
 6   State or Province  492 non-null    object
 7   City               492 non-null    object
 8   fuel               492 non-null    object
 9   seller_type        492 non-null    object
 10  transmission       492 non-null    object
 11  owner              492 non-null    object
 12  mileage            492 non-null    float64
 13  engine             492 non-null    int64
 14  max_power          492 non-null    float64
 15  seats              492 non-null    int64
 16  sold               492 non-null    object
 17  torque1            492 non-null    object
 18  rpm                492 non-null    object
dtypes: float64(2), int64(6), object(11)
memory usage: 76.9+ KB

In [ ]:
df1['torque1']=df1['torque1'].astype(float)

ValueError: ignored

In [ ]:
# Xóa ký tự "Nm" trong cột torque1 bị lỗi
df1['torque1']=df1['torque1'].str.replace('Nm','',regex=True)

In [ ]:
df1['torque1']=df1['torque1'].astype(float)
# đổi kiểu biến từ object sang float thì báo lỗi sai định dạng trong cột 'torque1'

ValueError: ignored

In [ ]:
df1[df1.torque1.str.contains('380')]

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,sold,torque1,rpm
751,779,Ford,2013,1075000,110000,Central,Michigan,Detroit,Diesel,Individual,Automatic,Third_Owner,12.8,2953,156.0,7,Y,380(38.7),2500

In [ ]:
# xuất ra file CSV để xử lý dòng Index 751 xóa 380 và phá ngoặc trong rpm
df1.to_csv('UserCarData1.csv')

In [ ]:
df1=pd.read_csv('UserCarData1.csv')

In [ ]:
df1

,Unnamed: 0,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,sold,torque1,rpm
0,2,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.7,1497,78.0,5,Y,12.7,"2,700"
1,3,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.0,1396,90.0,5,Y,22.4,1750-2750
2,4,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.1,1298,88.2,5,Y,11.5,"4,500"
3,6,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,Individual,Manual,First_Owner,17.3,1061,57.5,5,Y,7.8,"4,500"
4,16,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,Individual,Manual,Second_Owner,23.0,1396,90.0,5,Y,22.4,1750-2750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,7861,8083,Ford,2007,125000,110000,West,Washington,Yakima,Diesel,Individual,Manual,Third_Owner,17.8,1399,68.0,5,N,16.3,"2,000"
488,7882,8105,Honda,2006,160000,70000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,16.9,1497,100.0,5,N,13.5,"4,800"
489,7883,8106,Honda,2004,135000,120000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,13.0,1343,90.0,5,N,11.3,4700
490,7891,8114,Toyota,2010,425000,129000,South,North Carolina,Mooresville,Diesel,Individual,Manual,First_Owner,12.8,2494,102.0,8,N,20.4,1400-3400
491,7902,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.8,1493,110.0,5,N,24.0,"1,900-2,750"

In [ ]:
df1['torque1']=df1['torque1'].astype(float)

In [ ]:
# chuyển đổi đơn vị từ kgm thành Nm
df1['torque1']=df1['torque1']*9.8

In [ ]:
# Đổi tên cột từ "torque1" thành "torque"
df1=df1.rename(columns={'torque1':'torque'})

In [ ]:
# Re-index columns lại
df1=df1[['Sales_ID','name','year','selling_price','km_driven','Region','State or Province','City','fuel','seller_type','transmission','owner','mileage','engine','max_power','torque','rpm','seats','sold']]

In [ ]:
df1

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,rpm,seats,sold
0,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,Individual,Manual,Third_Owner,17.7,1497,78.0,124.46,"2,700",5,Y
1,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,Individual,Manual,First_Owner,23.0,1396,90.0,219.52,1750-2750,5,Y
2,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,16.1,1298,88.2,112.70,"4,500",5,Y
3,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,Individual,Manual,First_Owner,17.3,1061,57.5,76.44,"4,500",5,Y
4,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,Individual,Manual,Second_Owner,23.0,1396,90.0,219.52,1750-2750,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,8083,Ford,2007,125000,110000,West,Washington,Yakima,Diesel,Individual,Manual,Third_Owner,17.8,1399,68.0,159.74,"2,000",5,N
488,8105,Honda,2006,160000,70000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,16.9,1497,100.0,132.30,"4,800",5,N
489,8106,Honda,2004,135000,120000,West,California,Laguna Hills,Petrol,Individual,Manual,Second_Owner,13.0,1343,90.0,110.74,4700,5,N
490,8114,Toyota,2010,425000,129000,South,North Carolina,Mooresville,Diesel,Individual,Manual,First_Owner,12.8,2494,102.0,199.92,1400-3400,8,N
491,8125,Hyundai,2007,135000,119000,Central,Texas,Port Arthur,Diesel,Individual,Manual,Fourth_Above_Owner,16.8,1493,110.0,235.20,"1,900-2,750",5,N

Xử Lý Dãy số liệu torque theo NM. Tách ra bảng df2

In [ ]:
df2=df[df.torque.str.contains('kgm')==False]

In [ ]:
df2['torque']=df2['torque'].str.replace('Nm','',regex=True)

<ipython-input-137-459cb8526b39>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['torque']=df2['torque'].str.replace('Nm' or 'nm','',regex=True)

In [ ]:
df2['torque']=df2['torque'].str.replace('at','@',regex=True)

<ipython-input-138-f0b354f03c83>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['torque']=df2['torque'].str.replace('at','@',regex=True)

In [ ]:
df2['torque']=df2['torque'].str.replace('rpm','',regex=True)

<ipython-input-139-207257414275>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['torque']=df2['torque'].str.replace('rpm','',regex=True)

In [ ]:
df2.to_csv('UserCarData2.csv')

In [ ]:
df2['torque']=df2['torque'].str.replace('nm','',regex=True)

<ipython-input-140-334ba59240fc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['torque']=df2['torque'].str.replace('nm','',regex=True)

In [ ]:
df2

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
0,1,Maruti,2014,450000,145500,East,District of Columbia,Washington,Diesel,Individual,Manual,First_Owner,23.40,1248,74.00,190@ 2000,5,Y
1,2,Skoda,2014,370000,120000,East,New York,New York City,Diesel,Individual,Manual,Second_Owner,21.14,1498,103.52,250@ 1500-2500,5,Y
5,6,Hyundai,2017,440000,45000,East,New York,New York City,Petrol,Individual,Manual,First_Owner,20.14,1197,81.86,113.75@ 4000,5,Y
7,8,Maruti,2001,45000,5000,West,California,Los Angeles,Petrol,Individual,Manual,Second_Owner,16.10,796,37.00,59@ 2500,4,Y
8,9,Toyota,2011,350000,90000,West,California,Los Angeles,Diesel,Individual,Manual,First_Owner,23.59,1364,67.10,170@ 1800-2400,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7900,8123,Hyundai,2014,475000,80000,Central,Texas,Plano,Diesel,Individual,Manual,Second_Owner,22.54,1396,88.73,219.7@ 1500-2750,5,N
7901,8124,Hyundai,2013,320000,110000,Central,Texas,Plano,Petrol,Individual,Manual,First_Owner,18.50,1197,82.85,113.7@ 4000,5,N
7903,8126,Maruti,2009,382000,120000,Central,Texas,Port Arthur,Diesel,Individual,Manual,First_Owner,19.30,1248,73.90,190@ 2000,5,N
7904,8127,Tata,2013,290000,25000,East,Massachusetts,Lunenburg,Diesel,Individual,Manual,First_Owner,23.57,1396,70.00,140@ 1800-3000,5,N
7905,8128,Tata,2013,290000,25000,East,Maine,Augusta,Diesel,Individual,Manual,First_Owner,23.57,1396,70.00,140@ 1800-3000,5,N

In [ ]:
df2=df2[df2.torque.str.contains('@')]

In [ ]:
df2.to_csv('UserCarData3.csv')

In [ ]:
df2=pd.read_csv('UserCarData3.csv')

In [ ]:
df2[['torque1','rpm']]=df2['torque'].str.split("@",expand = True,regex=False)

In [ ]:
df2['torque1']=df2['torque1'].str.replace('KGM','',regex=True)

In [ ]:
df2['torque1']=df2['torque1'].astype(float)

ValueError: ignored

In [ ]:
df2['torque1']=df2['torque1'].str.replace('KGM','',regex=True)

In [ ]:
df2['torque1']=df2['torque1'].astype(float)

ValueError: ignored

In [ ]:
df2['torque1']=df2['torque1'].str.replace('NM','',regex=True)

In [ ]:
df2['torque1']=df2['torque1'].astype(float)

In [ ]:
df2=df2.drop(columns=['torque'])

In [ ]:
df2=df2.rename(columns={'torque1':'torque'})

In [ ]:
df2=df2[['Sales_ID','name','year','selling_price','km_driven','Region','State or Province','City','fuel','seller_type','transmission','owner','mileage','engine','max_power','torque','rpm','seats','sold']]

Tách DF3 thêm từ DF2 là danh sách ko có ký tự "@" ở Torque

In [ ]:
df3=df2[df2.torque.str.contains('@') == False]

In [ ]:
df3

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,sold
139,146,Volvo,2018,3400000,22000,East,District of Columbia,Washington,Diesel,Dealer,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
361,375,Volvo,2019,3800000,20000,Central,Michigan,Detroit,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
399,414,Volvo,2019,3800000,20000,West,California,Los Angeles,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
631,651,Volvo,2019,3800000,20000,Central,Illinois,Chicago,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
1050,1082,Volvo,2019,3800000,20000,Central,Texas,Pharr,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
1069,1101,Volvo,2019,3800000,20000,South,North Carolina,Greensboro,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
1088,1120,Volvo,2019,3800000,20000,East,New York,Elmira,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
1107,1139,Volvo,2019,3800000,20000,South,Arkansas,Little Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
1663,1714,Volvo,2019,3800000,20000,South,Georgia,Evans,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
1774,1829,Volvo,2019,3800000,20000,Central,Texas,Bryan,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,Y
2073,2138,Land,2013,1650000,64788,Central,Texas,Victoria,Diesel,Dealer,Automatic,First_Owner,0.0,2179,115.0,400 /2000,5,N
2548,2635,Volvo,2019,3800000,20000,Central,Kansas,Prairie Village,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
2581,2668,Volvo,2019,3800000,20000,East,Pennsylvania,Philadelphia,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
2986,3083,Volvo,2019,3800000,20000,Central,Texas,Eagle Pass,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
3151,3252,Volvo,2018,3400000,22000,Central,Texas,Friendswood,Diesel,Dealer,Automatic,First_Owner,18.0,1969,190.0,400,5,N
3307,3413,Volvo,2019,3800000,20000,East,Maine,Westbrook,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
3411,3521,Volvo,2019,3800000,20000,West,Washington,Vancouver,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
3719,3836,Volvo,2019,3800000,20000,South,Georgia,Martinez,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4096,4220,Volvo,2019,3800000,20000,West,California,Pacifica,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4115,4239,Volvo,2019,3800000,20000,Central,South Dakota,Sioux Falls,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4135,4260,Volvo,2019,3800000,20000,South,Georgia,College Park,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4199,4325,Volvo,2019,3800000,20000,East,New York,Syracuse,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4246,4374,Skoda,2006,280000,150000,West,Washington,Bremerton,Diesel,Individual,Manual,Third_Owner,18.7,1896,66.0,210 / 1900,5,N
4291,4419,Volvo,2019,3800000,20000,South,North Carolina,Salisbury,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4683,4820,Volvo,2019,3800000,20000,Central,Texas,League City,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
4944,5088,Volvo,2019,3800000,20000,Central,Indiana,Fort Wayne,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
5418,5573,Skoda,2007,300000,155000,West,Arizona,Gilbert,Diesel,Individual,Manual,First_Owner,18.7,1896,66.0,210 / 1900,5,N
5462,5619,Volvo,2019,3800000,20000,Central,Oklahoma,Bartlesville,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
5622,5786,Skoda,2007,110000,120000,Central,Texas,Sulphur Springs,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210 / 1900,5,N
5997,6171,Volvo,2019,3800000,20000,South,Florida,Royal Palm Beach,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
6040,6214,Volvo,2019,3800000,20000,East,Connecticut,North Haven,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
6238,6419,Skoda,2003,100000,250000,Central,Texas,Arlington,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210 / 1900,5,N
6376,6559,Volvo,2019,3800000,20000,East,Pennsylvania,Bethel Park,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
6395,6578,Volvo,2019,3800000,20000,West,Arizona,Glendale,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
6508,6694,Volvo,2019,3800000,20000,West,Colorado,Castle Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
6770,6964,Volvo,2019,3800000,20000,West,Washington,Tacoma,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
6958,7155,Skoda,2008,210000,120000,Central,Illinois,Buffalo Grove,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210 / 1900,5,N
7096,7297,Skoda,2010,355000,116000,Central,Illinois,Saint Charles,Diesel,Individual,Manual,First_Owner,18.7,1896,66.0,210 / 1900,5,N
7307,7517,Volvo,2018,5500000,50000,Central,Michigan,Adrian,Diesel,Individual,Automatic,First_Owner,11.2,1969,235.0,480,5,N
7322,7533,Skoda,2007,195000,175000,Central,Indiana,Mishawaka,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210 / 1900,5,N
7644,7863,Volvo,2019,3800000,20000,Central,Texas,Lufkin,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N
7712,7931,Volvo,2019,5500000,17000,South,Florida,Lehigh Acres,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,5,N

In [ ]:
df3[['torque1','rpm']]=df3['torque'].str.split("/",expand = True)

<ipython-input-173-dfa3613a3b77>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[['torque1','rpm']]=df3['torque'].str.split("/",expand = True)
<ipython-input-173-dfa3613a3b77>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[['torque1','rpm']]=df3['torque'].str.split("/",expand = True)

In [ ]:
df3=df3.drop(columns=['torque'])

In [ ]:
df3=df3.rename(columns={'torque1':'torque'})

In [ ]:
df3=df3[['Sales_ID','name','year','selling_price','km_driven','Region','State or Province','City','fuel','seller_type','transmission','owner','mileage','engine','max_power','torque','rpm','seats','sold']]

In [ ]:
df3

,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,rpm,seats,sold
139,146,Volvo,2018,3400000,22000,East,District of Columbia,Washington,Diesel,Dealer,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
361,375,Volvo,2019,3800000,20000,Central,Michigan,Detroit,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
399,414,Volvo,2019,3800000,20000,West,California,Los Angeles,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
631,651,Volvo,2019,3800000,20000,Central,Illinois,Chicago,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
1050,1082,Volvo,2019,3800000,20000,Central,Texas,Pharr,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
1069,1101,Volvo,2019,3800000,20000,South,North Carolina,Greensboro,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
1088,1120,Volvo,2019,3800000,20000,East,New York,Elmira,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
1107,1139,Volvo,2019,3800000,20000,South,Arkansas,Little Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
1663,1714,Volvo,2019,3800000,20000,South,Georgia,Evans,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
1774,1829,Volvo,2019,3800000,20000,Central,Texas,Bryan,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,Y
2073,2138,Land,2013,1650000,64788,Central,Texas,Victoria,Diesel,Dealer,Automatic,First_Owner,0.0,2179,115.0,400,2000,5,N
2548,2635,Volvo,2019,3800000,20000,Central,Kansas,Prairie Village,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
2581,2668,Volvo,2019,3800000,20000,East,Pennsylvania,Philadelphia,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
2986,3083,Volvo,2019,3800000,20000,Central,Texas,Eagle Pass,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
3151,3252,Volvo,2018,3400000,22000,Central,Texas,Friendswood,Diesel,Dealer,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
3307,3413,Volvo,2019,3800000,20000,East,Maine,Westbrook,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
3411,3521,Volvo,2019,3800000,20000,West,Washington,Vancouver,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
3719,3836,Volvo,2019,3800000,20000,South,Georgia,Martinez,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4096,4220,Volvo,2019,3800000,20000,West,California,Pacifica,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4115,4239,Volvo,2019,3800000,20000,Central,South Dakota,Sioux Falls,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4135,4260,Volvo,2019,3800000,20000,South,Georgia,College Park,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4199,4325,Volvo,2019,3800000,20000,East,New York,Syracuse,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4246,4374,Skoda,2006,280000,150000,West,Washington,Bremerton,Diesel,Individual,Manual,Third_Owner,18.7,1896,66.0,210,1900,5,N
4291,4419,Volvo,2019,3800000,20000,South,North Carolina,Salisbury,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4683,4820,Volvo,2019,3800000,20000,Central,Texas,League City,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
4944,5088,Volvo,2019,3800000,20000,Central,Indiana,Fort Wayne,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
5418,5573,Skoda,2007,300000,155000,West,Arizona,Gilbert,Diesel,Individual,Manual,First_Owner,18.7,1896,66.0,210,1900,5,N
5462,5619,Volvo,2019,3800000,20000,Central,Oklahoma,Bartlesville,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
5622,5786,Skoda,2007,110000,120000,Central,Texas,Sulphur Springs,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210,1900,5,N
5997,6171,Volvo,2019,3800000,20000,South,Florida,Royal Palm Beach,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
6040,6214,Volvo,2019,3800000,20000,East,Connecticut,North Haven,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
6238,6419,Skoda,2003,100000,250000,Central,Texas,Arlington,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210,1900,5,N
6376,6559,Volvo,2019,3800000,20000,East,Pennsylvania,Bethel Park,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
6395,6578,Volvo,2019,3800000,20000,West,Arizona,Glendale,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
6508,6694,Volvo,2019,3800000,20000,West,Colorado,Castle Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
6770,6964,Volvo,2019,3800000,20000,West,Washington,Tacoma,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
6958,7155,Skoda,2008,210000,120000,Central,Illinois,Buffalo Grove,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210,1900,5,N
7096,7297,Skoda,2010,355000,116000,Central,Illinois,Saint Charles,Diesel,Individual,Manual,First_Owner,18.7,1896,66.0,210,1900,5,N
7307,7517,Volvo,2018,5500000,50000,Central,Michigan,Adrian,Diesel,Individual,Automatic,First_Owner,11.2,1969,235.0,480,None,5,N
7322,7533,Skoda,2007,195000,175000,Central,Indiana,Mishawaka,Diesel,Individual,Manual,Second_Owner,18.7,1896,66.0,210,1900,5,N
7644,7863,Volvo,2019,3800000,20000,Central,Texas,Lufkin,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N
7712,7931,Volvo,2019,5500000,17000,South,Florida,Lehigh Acres,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400,None,5,N

In [ ]:
df_new= pd.concat([df1,df2,df3])

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7906 entries, 0 to 7712
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sales_ID           7906 non-null   int64
 1   name               7906 non-null   object
 2   year               7906 non-null   int64
 3   selling_price      7906 non-null   int64
 4   km_driven          7906 non-null   int64
 5   Region             7906 non-null   object
 6   State or Province  7906 non-null   object
 7   City               7906 non-null   object
 8   fuel               7906 non-null   object
 9   seller_type        7906 non-null   object
 10  transmission       7906 non-null   object
 11  owner              7906 non-null   object
 12  mileage            7906 non-null   float64
 13  engine             7906 non-null   int64
 14  max_power          7906 non-null   float64
 15  torque             7906 non-null   object
 16  rpm                7872 non-null   object
 17  seats              7906 non-null   int64
 18  sold               7906 non-null   object
dtypes: float64(2), int64(6), object(11)
memory usage: 1.2+ MB

In [ ]:
df_new.describe()

,Sales_ID,year,selling_price,km_driven,mileage,engine,max_power,seats
count,7906.000000,7906.000000,7.906000e+03,7.906000e+03,7906.000000,7906.000000,7906.000000,7906.000000
mean,4070.106248,2013.983936,6.498137e+05,6.918866e+04,19.419861,1458.708829,91.587374,5.416393
std,2345.770159,3.863695,8.135827e+05,5.679230e+04,4.036263,503.893057,35.747216,0.959208
min,1.000000,1994.000000,2.999900e+04,1.000000e+00,0.000000,624.000000,32.800000,2.000000
25%,2037.250000,2012.000000,2.700000e+05,3.500000e+04,16.780000,1197.000000,68.050000,5.000000
50%,4076.500000,2015.000000,4.500000e+05,6.000000e+04,19.300000,1248.000000,82.000000,5.000000
75%,6102.000000,2017.000000,6.900000e+05,9.542500e+04,22.320000,1582.000000,102.000000,5.000000
max,8128.000000,2020.000000,1.000000e+07,2.360457e+06,42.000000,3604.000000,400.000000,14.000000

In [ ]:
df_new.to_csv('UserCarData_Clean.csv')