In [ ]:
import pandas as pd
df=pd.read_csv('UserCarData_Clean.csv')

In [ ]:
df[df['name'].str.contains('Volvo')]
# https://www.car.info/en-se/volvo/xc40/xc40-d4-awd-ma8-2018-16517632/specs

,Unnamed: 0,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,rpm,seats,sold
648,156,171,Volvo,2017,10000000,30000,East,New York,New York City,Petrol,Individual,Automatic,First_Owner,42.0,1969,400.0,640.0,1740,4,Y
846,354,389,Volvo,2018,2475000,2000,Central,Michigan,Detroit,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
879,387,428,Volvo,2018,2475000,2000,West,California,Los Angeles,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
1102,610,665,Volvo,2018,2475000,2000,East,District of Columbia,Washington,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
1487,995,1096,Volvo,2018,2475000,2000,South,North Carolina,Garner,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7898,6508,6694,Volvo,2019,3800000,20000,West,Colorado,Castle Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,NaN,5,N
7899,6770,6964,Volvo,2019,3800000,20000,West,Washington,Tacoma,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,NaN,5,N
7902,7307,7517,Volvo,2018,5500000,50000,Central,Michigan,Adrian,Diesel,Individual,Automatic,First_Owner,11.2,1969,235.0,480.0,NaN,5,N
7904,7644,7863,Volvo,2019,3800000,20000,Central,Texas,Lufkin,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,NaN,5,N
7905,7712,7931,Volvo,2019,5500000,17000,South,Florida,Lehigh Acres,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,NaN,5,N

In [ ]:
# filter những động cơ có max power = 190 và torque 400Nm để nhập số vòng xoay 'rpm' vào 1,750 - 2,500
# https://www.car.info/en-se/volvo/xc40/xc40-d4-awd-ma8-2018-16517632/specs
df3.loc[(df3['max_power']==190) & (df3['torque']==400),'rpm'] = '1,750 - 2,500'

In [ ]:
df[df['name'].str.contains('Volvo')]

,Unnamed: 0,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,rpm,seats,sold
648,156,171,Volvo,2017,10000000,30000,East,New York,New York City,Petrol,Individual,Automatic,First_Owner,42.0,1969,400.0,640.0,1740,4,Y
846,354,389,Volvo,2018,2475000,2000,Central,Michigan,Detroit,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
879,387,428,Volvo,2018,2475000,2000,West,California,Los Angeles,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
1102,610,665,Volvo,2018,2475000,2000,East,District of Columbia,Washington,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
1487,995,1096,Volvo,2018,2475000,2000,South,North Carolina,Garner,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7898,6508,6694,Volvo,2019,3800000,20000,West,Colorado,Castle Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N
7899,6770,6964,Volvo,2019,3800000,20000,West,Washington,Tacoma,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N
7902,7307,7517,Volvo,2018,5500000,50000,Central,Michigan,Adrian,Diesel,Individual,Automatic,First_Owner,11.2,1969,235.0,480.0,NaN,5,N
7904,7644,7863,Volvo,2019,3800000,20000,Central,Texas,Lufkin,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N
7905,7712,7931,Volvo,2019,5500000,17000,South,Florida,Lehigh Acres,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N

In [ ]:
# filter những động cơ có max power = 235 và torque 480Nm để nhập số vòng xoay 'rpm' vào 1,750 - 2,250
df3.loc[(df3['max_power']==235) & (df3['torque']==480),'rpm'] = '1,750 - 2,250'

In [ ]:
df[['rpm_min','rpm_max']]=df['rpm'].str.split("-",expand = True)

In [ ]:
df.drop(columns='rpm')

,Unnamed: 0,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,...,transmission,owner,mileage,engine,max_power,torque,seats,sold,rpm_min,rpm_max
0,0,3,Honda,2006,158000,140000,Central,Illinois,Chicago,Petrol,...,Manual,Third_Owner,17.7,1497,78.0,124.46,5,Y,"2,700",None
1,1,4,Hyundai,2010,225000,127000,Central,Illinois,Chicago,Diesel,...,Manual,First_Owner,23.0,1396,90.0,219.52,5,Y,1750,2750
2,2,5,Maruti,2007,130000,120000,East,New York,New York City,Petrol,...,Manual,First_Owner,16.1,1298,88.2,112.70,5,Y,"4,500",None
3,3,7,Maruti,2007,96000,175000,West,California,Los Angeles,LPG,...,Manual,First_Owner,17.3,1061,57.5,76.44,5,Y,"4,500",None
4,4,18,Hyundai,2012,500000,53000,Central,Texas,Dallas,Diesel,...,Manual,Second_Owner,23.0,1396,90.0,219.52,5,Y,1750,2750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,7096,7297,Skoda,2010,355000,116000,Central,Illinois,Saint Charles,Diesel,...,Manual,First_Owner,18.7,1896,66.0,210.00,5,N,1900,None
7902,7307,7517,Volvo,2018,5500000,50000,Central,Michigan,Adrian,Diesel,...,Automatic,First_Owner,11.2,1969,235.0,480.00,5,N,"1,750","2,250"
7903,7322,7533,Skoda,2007,195000,175000,Central,Indiana,Mishawaka,Diesel,...,Manual,Second_Owner,18.7,1896,66.0,210.00,5,N,1900,None
7904,7644,7863,Volvo,2019,3800000,20000,Central,Texas,Lufkin,Diesel,...,Automatic,First_Owner,18.0,1969,190.0,400.00,5,N,"1,750","2,500"
7905,7712,7931,Volvo,2019,5500000,17000,South,Florida,Lehigh Acres,Diesel,...,Automatic,First_Owner,18.0,1969,190.0,400.00,5,N,"1,750","2,500"

In [ ]:
# Hàm lọc cột 'rpm_max' có giá trị là None/Null thì sẽ gán bằng giá trị rpm_min
df.loc[df['rpm_max'].isnull(),'rpm_max'] = df['rpm_min']

In [ ]:
# index lại các cột
df=df[['Sales_ID','name','year','selling_price','km_driven','Region','State or Province','City','fuel','seller_type','transmission','owner','mileage','engine','max_power','torque','rpm_min','rpm_max','seats','sold']]

In [ ]:
df['rpm_min']=df['rpm_min'].str.replace(',','',regex = False)

In [ ]:
df['rpm_max']=df['rpm_max'].str.replace(',','',regex = False)

In [ ]:
df['rpm_min']=df['rpm_min'].astype(float)

ValueError: ignored

In [ ]:
df.to_csv('UserCarData_Clean_rev1.csv')

In [ ]:
### hàm để thay giá trị NAN trong cột'rpm' thành giá trị cần '1,750 - 2,500' ( Ko Dùng, học để biết thêm)
df['rpm'].fillna('1,750 - 2,500',inplace = True)

In [ ]:
#data_df[pd.to_numeric(data_df['value'], errors='coerce').notna()]
df[pd.to_numeric(df['rpm_min'],errors='coerce')]

<ipython-input-41-7bcc2ce7b8d1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[pd.to_numeric(df['rpm_min'],errors='coerce')] = False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7906 entries, 0 to 7905
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sales_ID           7906 non-null   int64
 1   name               7906 non-null   object
 2   year               7906 non-null   int64
 3   selling_price      7906 non-null   int64
 4   km_driven          7906 non-null   int64
 5   Region             7906 non-null   object
 6   State or Province  7906 non-null   object
 7   City               7906 non-null   object
 8   fuel               7906 non-null   object
 9   seller_type        7906 non-null   object
 10  transmission       7906 non-null   object
 11  owner              7906 non-null   object
 12  mileage            7906 non-null   float64
 13  engine             7906 non-null   int64
 14  max_power          7906 non-null   float64
 15  torque             7906 non-null   float64
 16  rpm_min            7906 non-null   object
 17  rpm_max            7906 non-null   object
 18  seats              7906 non-null   int64
 19  sold               7906 non-null   object
dtypes: float64(3), int64(6), object(11)
memory usage: 1.2+ MB

In [ ]:
df[df['name'].str.contains('Volvo')]

,Unnamed: 0,Sales_ID,name,year,selling_price,km_driven,Region,State or Province,City,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,rpm,seats,sold
648,156,171,Volvo,2017,10000000,30000,East,New York,New York City,Petrol,Individual,Automatic,First_Owner,42.0,1969,400.0,640.0,1740,4,Y
846,354,389,Volvo,2018,2475000,2000,Central,Michigan,Detroit,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
879,387,428,Volvo,2018,2475000,2000,West,California,Los Angeles,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
1102,610,665,Volvo,2018,2475000,2000,East,District of Columbia,Washington,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
1487,995,1096,Volvo,2018,2475000,2000,South,North Carolina,Garner,Diesel,Dealer,Automatic,First_Owner,16.8,1984,150.0,350.0,1500-2750,5,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7898,6508,6694,Volvo,2019,3800000,20000,West,Colorado,Castle Rock,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N
7899,6770,6964,Volvo,2019,3800000,20000,West,Washington,Tacoma,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N
7902,7307,7517,Volvo,2018,5500000,50000,Central,Michigan,Adrian,Diesel,Individual,Automatic,First_Owner,11.2,1969,235.0,480.0,"1,750 - 2,500",5,N
7904,7644,7863,Volvo,2019,3800000,20000,Central,Texas,Lufkin,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N
7905,7712,7931,Volvo,2019,5500000,17000,South,Florida,Lehigh Acres,Diesel,Individual,Automatic,First_Owner,18.0,1969,190.0,400.0,"1,750 - 2,500",5,N